// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/genesis/EclipseDawnVariant.tsx": () => import("../components/mockups/genesis/EclipseDawnVariant.tsx"),
  "./components/mockups/genesis/ThresholdCommandVariant.tsx": () => import("../components/mockups/genesis/ThresholdCommandVariant.tsx")
};
